version: '3.8'

services:
  imaginary-rs:
    image: ghcr.io/your-org/imaginary-rs:latest
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=warn
      - IMAGINARY_ALLOW_INSECURE=0
      - IMAGINARY_API_KEY_FILE=/run/secrets/api_key
      - IMAGINARY_SALT_FILE=/run/secrets/api_salt
    volumes:
      - ./config/production.toml:/usr/local/etc/imaginary-rs/config/default.toml:ro
    secrets:
      - api_key
      - api_salt
    healthcheck:
      test: ["/usr/local/bin/imaginary-rs", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - imaginary-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl/certs:ro
    depends_on:
      - imaginary-rs
    networks:
      - imaginary-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M

secrets:
  api_key:
    external: true
  api_salt:
    external: true

networks:
  imaginary-network:
    driver: overlay
    attachable: true
