[server]
port = 8080
host = "127.0.0.1"
read_timeout = 30
write_timeout = 30
concurrency = 4

[security]
key = ""
salt = ""
allowed_origins = ["*"]

[storage]
temp_dir = "/tmp"
max_cache_size = 104857600  # 100 MB